[package]
name = "backup-client"
version = "0.2.1"
description = "Backup Client"
authors = ["CodesDevs"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }
cc = "1.0"

[dependencies]
tauri = { version = "1.0", features = ["api-all", "system-tray"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0.1"
notify = "5.0"
winreg = "0.10"


[features]
custom-protocol = ["tauri/custom-protocol"]

[package.metadata.tauri]
windows-attributes = { window = true }
build = "build.rs"
