[package]
name = "backup-client"
version = "0.2.2"
description = "Backup Client"
authors = ["CodesDevs"]
edition = "2021"

[dependencies]
cron = "0.10"
tauri = { version = "1.0", features = ["system-tray"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0.1"
notify = "5.0"
winreg = "0.10"
chrono = "0.4"
log = "0.4"
env_logger = "0.10"

[build-dependencies]
tauri-build = { version = "1", features = [] }
cc = "1.0"

[features]
custom-protocol = ["tauri/custom-protocol"]

[package.metadata.tauri]
build = "build.rs"

[package.metadata.winres]
windows = true

[package.metadata.tauri.windows]
windows-subsystem = "windows"
